import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Daria ID",
  description: "Generated by create MOSTECH INDONESIA © 2025 DARIA",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Kelas antialiased di Tailwind CSS digunakan untuk menghaluskan tepi font (anti-aliasing) agar teks terlihat lebih halus dan jernih di layar. */}
        {children}
      </body>
    </html>
  );
}
